### ISSUE TITLE
Inconsistent types in register vs get signed statement

### ISSUE THREAD

**Issue by JAG-UK** [scitt-community/py-scrapi#2]
The wrapper for register_signed_statement takes bytes (a serialised Sign1Message) but resolve_signed_statement returns a pycose Sign1Message object.

In pursuit of spreading the joy and happiness of CBOR and COSE I suggest we harmonise on the Sign1Message object

**Comment by robinbryce** [comment]
I like this. There are some spots where working exclusively with Sign1Message can force re-encoding. This should have the same results, but losing track of how the message was originally encoded can prevent that. Possibly we want a means to retain or recover the raw bytes ?

**Comment by JAG-UK** [comment]
Fixed in PR 9
